### ISSUE TITLE
fastener directions

### ISSUE THREAD

**Issue by julianstirling** [Wakoma/nimble#103] opened 2024-12-19 15:30 UTC
Hi @jmwright 

I updated everything and ran the tests. Many of the fasteners seem to be going in the wrong direction

![Western_Digital_Blue_SSD_shelf_annotated](https://github.com/user-attachments/assets/03f9be18-d858-4c47-8486-af457b5f7c7d)
![Hex_shelf_annotated](https://github.com/user-attachments/assets/5aff7110-90c7-405f-9263-9143ae8d76b2)
![NUC8I5BEH_shelf_annotated](https://github.com/user-attachments/assets/c3de3cdc-c3d5-4bd0-972a-9a66dbf88bcc)
![Western_Digital_Red_HDD_shelf_annotated](https://github.com/user-attachments/assets/61f29e6e-9ba4-4562-ab6e-6a10a9a95e13)

**Comment by jmwright** [comment] 2024-12-19 15:32
I feel like we had this issue once before and it was because an old version of cq-annotate got into the mix somehow. Did you run the tests locally? Was it in a fresh environment?

**Comment by julianstirling** [comment] 2024-12-19 15:34
fresh environment, ran the setup. If we are going to run the test each time in CI maybe we should save the images as arifacts so we can check what the CI produces, rather than the images being lost each time?

**Comment by jmwright** [comment] 2024-12-19 16:16
> maybe we should save the images as arifacts so we can check what the CI produces, rather than the images being lost each time?

Yeah, good idea.

**Comment by jmwright** [comment] 2024-12-19 17:00
I can reproduce this now, but I am not sure what has changed between when the assembly lines PR was first merged (it was working then) and now. I will look into it.

**Comment by jmwright** [comment] 2024-12-19 17:40
Sigh...I can't reproduce this bug with the cq-annotate tests (simplified similar assembly works). This is going to take some more time than I hoped to debug.

**Comment by jmwright** [comment] 2024-12-19 21:26
Apparently VTK actors use degrees for rotation. CadQuery Location rotation angles are in radians and the original code did not convert between the two. That is fixed in #106 by pinning to the fixed version of the PNG render plugin.

**Comment by jmwright** [comment] 2024-12-22 12:09
#106 was merged, so I'm closing this.

**Closed by jmwright** 2024-12-22 12:09 UTC
